package com.model;
// Generated Oct 26, 2020 12:55:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ConsulDet generated by hbm2java
 */
public class ConsulDet  implements java.io.Serializable {


     private Integer consulId;
     private String userUsername;
     private Date consulDate;
     private Date consulTime;
     private String consulDoctor;
     private String consulVia;

    public ConsulDet() {
    }

    public ConsulDet(String userUsername, Date consulDate, Date consulTime, String consulDoctor, String consulVia) {
       this.userUsername = userUsername;
       this.consulDate = consulDate;
       this.consulTime = consulTime;
       this.consulDoctor = consulDoctor;
       this.consulVia = consulVia;
    }
   
    public Integer getConsulId() {
        return this.consulId;
    }
    
    public void setConsulId(Integer consulId) {
        this.consulId = consulId;
    }
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public Date getConsulDate() {
        return this.consulDate;
    }
    
    public void setConsulDate(Date consulDate) {
        this.consulDate = consulDate;
    }
    public Date getConsulTime() {
        return this.consulTime;
    }
    
    public void setConsulTime(Date consulTime) {
        this.consulTime = consulTime;
    }
    public String getConsulDoctor() {
        return this.consulDoctor;
    }
    
    public void setConsulDoctor(String consulDoctor) {
        this.consulDoctor = consulDoctor;
    }
    public String getConsulVia() {
        return this.consulVia;
    }
    
    public void setConsulVia(String consulVia) {
        this.consulVia = consulVia;
    }




}


