package com.model;
// Generated Oct 26, 2020 12:55:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userdet generated by hbm2java
 */
public class Userdet  implements java.io.Serializable {


     private Integer userdetId;
     private String userUsername;
     private String userdetEmail;
     private String userdetFullname;
     private String userdetNickame;
     private Date userdetBday;
     private String userdetPhone;
     private String userdetPackage;

    public Userdet() {
    }

    public Userdet(String userUsername, String userdetEmail, String userdetFullname, String userdetNickame, Date userdetBday, String userdetPhone, String userdetPackage) {
       this.userUsername = userUsername;
       this.userdetEmail = userdetEmail;
       this.userdetFullname = userdetFullname;
       this.userdetNickame = userdetNickame;
       this.userdetBday = userdetBday;
       this.userdetPhone = userdetPhone;
       this.userdetPackage = userdetPackage;
    }
   
    public Integer getUserdetId() {
        return this.userdetId;
    }
    
    public void setUserdetId(Integer userdetId) {
        this.userdetId = userdetId;
    }
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public String getUserdetEmail() {
        return this.userdetEmail;
    }
    
    public void setUserdetEmail(String userdetEmail) {
        this.userdetEmail = userdetEmail;
    }
    public String getUserdetFullname() {
        return this.userdetFullname;
    }
    
    public void setUserdetFullname(String userdetFullname) {
        this.userdetFullname = userdetFullname;
    }
    public String getUserdetNickame() {
        return this.userdetNickame;
    }
    
    public void setUserdetNickame(String userdetNickame) {
        this.userdetNickame = userdetNickame;
    }
    public Date getUserdetBday() {
        return this.userdetBday;
    }
    
    public void setUserdetBday(Date userdetBday) {
        this.userdetBday = userdetBday;
    }
    public String getUserdetPhone() {
        return this.userdetPhone;
    }
    
    public void setUserdetPhone(String userdetPhone) {
        this.userdetPhone = userdetPhone;
    }
    public String getUserdetPackage() {
        return this.userdetPackage;
    }
    
    public void setUserdetPackage(String userdetPackage) {
        this.userdetPackage = userdetPackage;
    }




}


